### ISSUE TITLE
Codec error decoding image

### ISSUE THREAD

**Issue by BoHellgren** [stormy-ua/dog-breeds-classification#7]
Running stanford_ds_to_tfrecords ends with an error message  on line 33
img_raw = open(path, 'r').read()

This happens on the first image processed, every time. This is on Windows 10.  I get
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 251: character maps to undefined

I tried 
img_raw = open(path, 'r', encoding=None).read()
but that did not work. Any ideas? Here is the complete log:

D:\dog-breeds-classification>python -m src.data_preparation.stanford_ds_to_tfrecords
2019-03-10 11:33:12.677523: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled t
o use: AVX2
WARNING:tensorflow:From D:\dog-breeds-classification\src\freezing\freeze.py:49: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and w
ill be removed in a future version.
Instructions for updating:
Use tf.gfile.GFile.
2019-03-10 11:33:13.273581: W tensorflow/core/framework/op_def_util.cc:355] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphD
ef version 9. Use tf.nn.batch_normalization().
n02085620-Chihuahua
n02085620_1073
{'breed': 'chihuahua', 'bndbox_xmin': '0', 'bndbox_ymin': '27', 'bndbox_xmax': '312', 'bndbox_ymax': '498'}
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\dog-breeds-classification\src\data_preparation\stanford_ds_to_tfrecords.py", line 73, in <module>
    image = parse_image(breed_dir, annotation_file)
  File "D:\dog-breeds-classification\src\data_preparation\stanford_ds_to_tfrecords.py", line 33, in parse_image
    img_raw = open(path, 'r').read()
  File "D:\Python\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 251: character maps to undefined

**Comment by BoHellgren** [comment]
I fixed this by changing line 33 to
img_raw = open(path, 'rb').read()

Now i have all the Stanford Dogs input in the stanford.tfrecords file. But I have not figured out how to use it with the Tensorflow for Poets scripts.
